<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE beans [
    <!ELEMENT beans (bean*)>
    <!ELEMENT bean (property*)>
    <!ELEMENT property (#PCDATA)>

    <!ATTLIST bean id ID #REQUIRED>
    <!ATTLIST bean class CDATA #IMPLIED>
    <!ATTLIST property name CDATA #IMPLIED>
    <!ATTLIST property ref IDREF #IMPLIED>
]>

<beans>
    <bean id="userBasicDAO" class="com.liukai.qqzone.dao.impl.UserBasicDAOImpl"/>
    <bean id="topicDAO" class="com.liukai.qqzone.dao.impl.TopicDAOImpl"/>

    <bean id="userBasicService" class="com.liukai.qqzone.service.impl.UserBasicServiceImpl">
        <property name="userBasicDAO" ref="userBasicDAO"/>
    </bean>

    <bean id="topicService" class="com.liukai.qqzone.service.impl.TopicServiceImpl">
        <property name="topicDAO" ref="topicDAO"/>
    </bean>

    <bean id="user" class="com.liukai.qqzone.controller.UserController">
        <property name="userBasicService" ref="userBasicService"/>
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="page" class="com.liukai.qqzone.controller.PageController"/>
    <bean id="topic" class="com.liukai.qqzone.controller.TopicController">
        <property name="topicService" ref="topicService"/>
    </bean>

</beans>